FROM golang:1.26.3-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o main ./cmd/app/

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/main .

EXPOSE 8092

CMD ["./main"]