package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"log"
	"math/rand"
	"net/http"
	"sync"
	"time"
)

var (
	baseURL  = flag.String("url", "http://localhost:8080", "API base URL")
	botCount = flag.Int("bots", 5, "Number of concurrent bots")
)

type Bot struct {
	ID           int
	Email        string
	Password     string
	AccessToken  string
	RefreshToken string
	TaskIDs      []string
	client       *http.Client
}

func main() {
	flag.Parse()
	log.Printf("Starting %d bots against %s", *botCount, *baseURL)

	var wg sync.WaitGroup
	for i := 0; i < *botCount; i++ {
		wg.Add(1)
		go func(id int) {
			defer wg.Done()
			bot := NewBot(id)
			bot.Run()
		}(i)
		time.Sleep(500 * time.Millisecond)
	}
	wg.Wait()
}

func NewBot(id int) *Bot {
	return &Bot{
		ID:       id,
		Email:    fmt.Sprintf("bot%d_%d@example.com", id, time.Now().UnixNano()),
		Password: "password123",
		client:   &http.Client{Timeout: 10 * time.Second},
	}
}

func (b *Bot) Run() {
	if err := b.Register(); err != nil {
		log.Printf("[bot %d] register failed: %v", b.ID, err)
		return
	}
	log.Printf("[bot %d] registered as %s", b.ID, b.Email)

	if err := b.Login(); err != nil {
		log.Printf("[bot %d] login failed: %v", b.ID, err)
		return
	}
	log.Printf("[bot %d] logged in", b.ID)

	for {
		action := pickAction()
		err := b.Do(action)
		if err != nil {
			log.Printf("[bot %d] action %s failed: %v", b.ID, action, err)
		} else {
			log.Printf("[bot %d] action %s succes", b.ID, action)
		}
		time.Sleep(time.Duration(1+rand.Intn(5)) * time.Second)
	}
}

func pickAction() string {
	r := rand.Intn(100)
	switch {
	case r < 40:
		return "create_task"
	case r < 60:
		return "update_task"
	case r < 75:
		return "create_note"
	case r < 90:
		return "get_tasks"
	case r < 95:
		return "delete_task"
	default:
		return "refresh_token"
	}
}

func (b *Bot) Do(action string) error {
	switch action {
	case "create_task":
		return b.CreateTask()
	case "update_task":
		return b.UpdateRandomTask()
	case "create_note":
		return b.CreateNote()
	case "get_tasks":
		return b.GetTasks()
	case "delete_task":
		return b.DeleteRandomTask()
	case "refresh_token":
		return b.Refresh()
	}
	return nil
}

func (b *Bot) Register() error {
	body := map[string]string{
		"name":     fmt.Sprintf("Bot%d", b.ID),
		"email":    b.Email,
		"password": b.Password,
	}
	_, err := b.do("POST", "/api/register", body, false)
	return err
}

func (b *Bot) Login() error {
	body := map[string]string{
		"email":    b.Email,
		"password": b.Password,
	}
	resp, err := b.do("POST", "/api/login", body, false)
	if err != nil {
		return err
	}

	var tokens struct {
		AccessToken  string `json:"access_token"`
		RefreshToken string `json:"refresh_token"`
	}
	if err := json.Unmarshal(resp, &tokens); err != nil {
		return err
	}
	b.AccessToken = tokens.AccessToken
	b.RefreshToken = tokens.RefreshToken
	return nil
}

func (b *Bot) Refresh() error {
	body := map[string]string{"refresh_token": b.RefreshToken}
	resp, err := b.do("POST", "/api/refresh", body, false)
	if err != nil {
		return err
	}
	var tokens struct {
		AccessToken  string `json:"access_token"`
		RefreshToken string `json:"refresh_token"`
	}
	if err := json.Unmarshal(resp, &tokens); err != nil {
		return err
	}
	b.AccessToken = tokens.AccessToken
	b.RefreshToken = tokens.RefreshToken
	return nil
}

func (b *Bot) CreateTask() error {
	statuses := []string{"todo", "in_progress", "done", "cancelled"}
	body := map[string]any{
		"title":       fmt.Sprintf("Task %d-%d", b.ID, rand.Intn(10000)),
		"description": "Generated by load tester",
		"status":      statuses[rand.Intn(2)],
		"priority":    1 + rand.Intn(4),
		"deadline":    time.Now().Add(time.Duration(1+rand.Intn(48)) * time.Hour).Format(time.RFC3339),
	}
	resp, err := b.do("POST", "/api/tasks", body, true)
	if err != nil {
		return err
	}
	var created struct {
		Data struct {
			ID string `json:"id"`
		} `json:"data"`
	}
	if err := json.Unmarshal(resp, &created); err == nil && created.Data.ID != "" {
		b.TaskIDs = append(b.TaskIDs, created.Data.ID)
	}
	return nil
}

func (b *Bot) UpdateRandomTask() error {
	if len(b.TaskIDs) == 0 {
		return nil
	}
	taskID := b.TaskIDs[rand.Intn(len(b.TaskIDs))]
	statuses := []string{"in_progress", "done", "cancelled"}
	body := map[string]any{
		"status": statuses[rand.Intn(len(statuses))],
	}
	_, err := b.do("PATCH", "/api/tasks/"+taskID, body, true)
	return err
}

func (b *Bot) DeleteRandomTask() error {
	if len(b.TaskIDs) == 0 {
		return nil
	}
	idx := rand.Intn(len(b.TaskIDs))
	taskID := b.TaskIDs[idx]
	_, err := b.do("DELETE", "/api/tasks/"+taskID, nil, true)
	if err == nil {
		b.TaskIDs = append(b.TaskIDs[:idx], b.TaskIDs[idx+1:]...)
	}
	return err
}

func (b *Bot) CreateNote() error {
	if len(b.TaskIDs) == 0 {
		return nil
	}
	taskID := b.TaskIDs[rand.Intn(len(b.TaskIDs))]
	body := map[string]any{
		"text": fmt.Sprintf("Note from bot %d at %s", b.ID, time.Now().Format(time.Kitchen)),
	}
	_, err := b.do("POST", "/api/tasks/"+taskID+"/notes", body, true)
	return err
}

func (b *Bot) GetTasks() error {
	_, err := b.do("GET", "/api/tasks?page=1&limit=10", nil, true)
	return err
}

func (b *Bot) do(method, path string, body any, withAuth bool) ([]byte, error) {
	var reqBody io.Reader
	if body != nil {
		data, _ := json.Marshal(body)
		reqBody = bytes.NewReader(data)
	}

	req, err := http.NewRequest(method, *baseURL+path, reqBody)
	if err != nil {
		return nil, err
	}
	if body != nil {
		req.Header.Set("Content-Type", "application/json")
	}
	if withAuth && b.AccessToken != "" {
		req.Header.Set("Authorization", "Bearer "+b.AccessToken)
	}

	resp, err := b.client.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	respBody, _ := io.ReadAll(resp.Body)
	if resp.StatusCode >= 400 {
		return respBody, fmt.Errorf("status %d: %s", resp.StatusCode, string(respBody))
	}
	return respBody, nil
}
