events {
    worker_connections 1024;
}

http {
    upstream auth_service {
        server auth_service:8091;
    }

    upstream task_service {
        server task_service:8090;
    }

    server {
        listen 80;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       
        #
        location /api/register {
            proxy_pass http://auth_service;
        }

        location /api/login {
            proxy_pass http://auth_service;
        }

        location /api/refresh {
            proxy_pass http://auth_service;
        }

        location /api/logout {
            proxy_pass http://auth_service;
        }

        location /api/profile {
            proxy_pass http://auth_service;
        }

        
        location /api/ {
            proxy_pass http://task_service;
        }


        location /healthz/auth {
            rewrite ^/healthz/auth$ /healthz break;
            proxy_pass http://auth_service;
        }

        location /readyz/auth {
            rewrite ^/readyz/auth$ /readyz break;
            proxy_pass http://auth_service;
        }

        location /healthz/tasks {
            rewrite ^/healthz/tasks$ /healthz break;
            proxy_pass http://task_service;
        }

        location /readyz/tasks {
            rewrite ^/readyz/tasks$ /readyz break;
            proxy_pass http://task_service;
        }
    }
}